// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/get_auth": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Update short link",
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "ShortLink"
                ],
                "summary": "ShortLink",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.GroupMPT"
                            }
                        }
                    },
                    "503": {
                        "description": "Технический перерыв",
                        "schema": {
                            "$ref": "#/definitions/model.GroupMarlo"
                        }
                    }
                }
            }
        },
        "/groupmarlo": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create a GroupMarlo record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GroupMarlo"
                ],
                "parameters": [
                    {
                        "description": "GroupMarlo object that needs to be created",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.GroupMarlo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateGroupMarlo"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateGroupMarlo"
                        }
                    }
                }
            }
        },
        "/groupmarlo/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Reade a GroupMarlo record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GroupMarlo"
                ],
                "summary": "Reade a GroupMarlo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateGroupMarlo"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateGroupMarlo"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Update a GroupMarlo record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GroupMarlo"
                ],
                "summary": "UPDATE a GroupMarlo",
                "parameters": [
                    {
                        "description": "GroupMarlo object that needs to be Updated",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.GroupMarlo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateGroupMarlo"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateGroupMarlo"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Reade a GroupMarlo record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GroupMarlo"
                ],
                "summary": "DELETE a GroupMarlo",
                "parameters": [
                    {
                        "description": "GroupMarlo object that needs to be deleted",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.GroupMarlo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateGroupMarlo"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateGroupMarlo"
                        }
                    }
                }
            }
        },
        "/groupmarlo_all": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Reading a GroupMarlo all items",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GroupMarlo"
                ],
                "summary": "Read All GroupMPT records",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateGroupMarloArr"
                            }
                        }
                    },
                    "500": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateGroupMarloArr"
                        }
                    }
                }
            }
        },
        "/groupmpt": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "create item of mpt group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GroupMPT"
                ],
                "summary": "Create group mpt",
                "parameters": [
                    {
                        "description": "GroupMPT object that needs to be found",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.GroupMPT"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateGroupMPT"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateGroupMPT"
                        }
                    }
                }
            }
        },
        "/groupmpt/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Reading a GroupMPT item by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GroupMPT"
                ],
                "summary": "Read a GroupMPT by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateGroupMPT"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateGroupMPT"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create a new GroupMPT record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GroupMPT"
                ],
                "summary": "update a GroupMPT",
                "parameters": [
                    {
                        "description": "GroupMPT object that needs to be updated",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.GroupMPT"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateGroupMPT"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateGroupMPT"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Delete a GroupMPT record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GroupMPT"
                ],
                "summary": "Delete a GroupMPT",
                "parameters": [
                    {
                        "description": "GroupMPT object that needs to be deleted",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.GroupMPT"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateGroupMPT"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateGroupMPT"
                        }
                    }
                }
            }
        },
        "/groupmpt_all": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Reading a GroupMPT items",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GroupMPT"
                ],
                "summary": "Read All GroupMPT records",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateGroupMPTArr"
                            }
                        }
                    },
                    "500": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateGroupMPTArr"
                        }
                    }
                }
            }
        },
        "/logs": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create a new log entry record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logs"
                ],
                "summary": "Create a new log entry",
                "parameters": [
                    {
                        "description": "Logs object that needs to be created",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Logs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateLogs"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateLogs"
                        }
                    }
                }
            }
        },
        "/logs/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Reading a log entry item by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logs"
                ],
                "summary": "Read a log entry by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateLogs"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateLogs"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Update a log entry record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logs"
                ],
                "summary": "Update a log entry",
                "parameters": [
                    {
                        "description": "Logs object that needs to be updated",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Logs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateLogs"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateLogs"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Delete a log entry record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logs"
                ],
                "summary": "Delete a log entry",
                "parameters": [
                    {
                        "description": "Logs object that needs to be deleted",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Logs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateLogs"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateLogs"
                        }
                    }
                }
            }
        },
        "/practice": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create a new practice record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Practices"
                ],
                "summary": "Create a new practice",
                "parameters": [
                    {
                        "description": "Practice object that needs to be created",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Practices"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreatePractice"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreatePractice"
                        }
                    }
                }
            }
        },
        "/practice/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Reading a practice item by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Practices"
                ],
                "summary": "Read a practice by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreatePractice"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreatePractice"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Update a practice record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Practices"
                ],
                "summary": "Update a practice",
                "parameters": [
                    {
                        "description": "Practice object that needs to be updated",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Practices"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreatePractice"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreatePractice"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Delete a practice record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Practices"
                ],
                "summary": "Delete a practice",
                "parameters": [
                    {
                        "description": "Practice object that needs to be deleted",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Practices"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreatePractice"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreatePractice"
                        }
                    }
                }
            }
        },
        "/practice_all": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Reading all practices",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Practices"
                ],
                "summary": "Read all practices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreatePracticeArr"
                            }
                        }
                    },
                    "500": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreatePracticeArr"
                        }
                    }
                }
            }
        },
        "/practiceconfig": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create a new practice configuration record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PracticeConfig"
                ],
                "summary": "Create a new practice configuration",
                "parameters": [
                    {
                        "description": "PracticeConfig object that needs to be created",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PracticeConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreatePracticeConfig"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreatePracticeConfig"
                        }
                    }
                }
            }
        },
        "/practiceconfig/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Reading a practice configuration item by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PracticeConfig"
                ],
                "summary": "Read a practice configuration by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreatePracticeConfig"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreatePracticeConfig"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Update a practice configuration record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PracticeConfig"
                ],
                "summary": "Update a practice configuration",
                "parameters": [
                    {
                        "description": "PracticeConfig object that needs to be updated",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PracticeConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreatePracticeConfig"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreatePracticeConfig"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Delete a practice configuration record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PracticeConfig"
                ],
                "summary": "Delete a practice configuration",
                "parameters": [
                    {
                        "description": "PracticeConfig object that needs to be deleted",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PracticeConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreatePracticeConfig"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreatePracticeConfig"
                        }
                    }
                }
            }
        },
        "/practiceconfig_all": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Reading all practices configs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PracticeConfig"
                ],
                "summary": "Read all practices configs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreatePracticeConfigArr"
                            }
                        }
                    },
                    "500": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreatePracticeConfigArr"
                        }
                    }
                }
            }
        },
        "/practiceday": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create a new practice day record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PracticeDays"
                ],
                "summary": "Create a new practice day",
                "parameters": [
                    {
                        "description": "PracticeDay object that needs to be created",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PracticeDays"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreatePracticedays"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreatePracticedays"
                        }
                    }
                }
            }
        },
        "/practiceday/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Reading a practice day item by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PracticeDays"
                ],
                "summary": "Read a practice day by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreatePracticedays"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreatePracticedays"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Update a practice day record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PracticeDays"
                ],
                "summary": "Update a practice day",
                "parameters": [
                    {
                        "description": "PracticeDay object that needs to be updated",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PracticeDays"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreatePracticedays"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreatePracticedays"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Delete a practice day record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PracticeDays"
                ],
                "summary": "Delete a practice day",
                "parameters": [
                    {
                        "description": "PracticeDay object that needs to be deleted",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PracticeDays"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreatePracticedays"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreatePracticedays"
                        }
                    }
                }
            }
        },
        "/practiceday_all": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Reading all practices days",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PracticeDays"
                ],
                "summary": "Read all practices days",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreatePracticedaysArr"
                            }
                        }
                    },
                    "500": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreatePracticedaysArr"
                        }
                    }
                }
            }
        },
        "/practiceschedule": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create a new practice schedule record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PracticeShedule"
                ],
                "summary": "Create a new practice schedule",
                "parameters": [
                    {
                        "description": "PracticeShedule object that needs to be created",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PracticeShedule"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreatepracticeShedule"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreatepracticeShedule"
                        }
                    }
                }
            }
        },
        "/practiceschedule/:{id}": {
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Delete a practice schedule record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PracticeShedule"
                ],
                "summary": "Delete a practice schedule",
                "parameters": [
                    {
                        "description": "PracticeShedule object that needs to be deleted",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PracticeShedule"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreatepracticeShedule"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreatepracticeShedule"
                        }
                    }
                }
            }
        },
        "/practiceschedule/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Reading a practice schedule item by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PracticeShedule"
                ],
                "summary": "Read a practice schedule by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreatepracticeShedule"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreatepracticeShedule"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Update a practice schedule record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PracticeShedule"
                ],
                "summary": "Update a practice schedule",
                "parameters": [
                    {
                        "description": "PracticeShedule object that needs to be updated",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PracticeShedule"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreatepracticeShedule"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreatepracticeShedule"
                        }
                    }
                }
            }
        },
        "/practiceschedule_all": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Reading all practice shedule",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PracticeShedule"
                ],
                "summary": "Read all practice shedule",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreatepracticeSheduleArr"
                            }
                        }
                    },
                    "500": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreatepracticeSheduleArr"
                        }
                    }
                }
            }
        },
        "/status": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create a new status record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status"
                ],
                "summary": "Create a new status",
                "parameters": [
                    {
                        "description": "Status object that needs to be created",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Status"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateStatus"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateStatus"
                        }
                    }
                }
            }
        },
        "/status/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Reading a status item by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status"
                ],
                "summary": "Read a status by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateStatus"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateStatus"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Update a status record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status"
                ],
                "summary": "Update a status",
                "parameters": [
                    {
                        "description": "Status object that needs to be updated",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Status"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateStatus"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateStatus"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Delete a status record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status"
                ],
                "summary": "Delete a status",
                "parameters": [
                    {
                        "description": "Status object that needs to be deleted",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Status"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateStatus"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateStatus"
                        }
                    }
                }
            }
        },
        "/status_all": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Reading all logs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logs"
                ],
                "summary": "Read all Logs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateLogsArr"
                            }
                        }
                    },
                    "500": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateLogsArr"
                        }
                    }
                }
            }
        },
        "/user": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create a new user record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "User object that needs to be created",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateUser"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateUser"
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Reading a user item by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Read a user by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateUser"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateUser"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Update a user record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update a user",
                "parameters": [
                    {
                        "description": "User object that needs to be updated",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateUser"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateUser"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Delete a user record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Delete a user",
                "parameters": [
                    {
                        "description": "User object that needs to be deleted",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateUser"
                            }
                        }
                    },
                    "503": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateUser"
                        }
                    }
                }
            }
        },
        "/user_all": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Reading all users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Read all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResponseUserCreateUserArr"
                            }
                        }
                    },
                    "500": {
                        "description": "Технические шоколадки",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseUserCreateUserArr"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.GroupMPT": {
            "type": "object",
            "required": [
                "group_number"
            ],
            "properties": {
                "group_number": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "model.GroupMarlo": {
            "type": "object",
            "properties": {
                "group_number": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "model.Logs": {
            "type": "object",
            "required": [
                "action",
                "date",
                "user_id"
            ],
            "properties": {
                "action": {
                    "description": "User   User      ` + "`" + `json:\"user\" gorm:\"foreignKey:UserId;references:ID\"` + "`" + `",
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "model.PracticeConfig": {
            "type": "object",
            "required": [
                "group_marlo_id",
                "group_mpt_id",
                "id",
                "practice_id",
                "student_id",
                "supervisor_id"
            ],
            "properties": {
                "group_marlo_id": {
                    "type": "integer"
                },
                "group_mpt_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "practice_id": {
                    "type": "integer"
                },
                "student_id": {
                    "type": "integer"
                },
                "supervisor_id": {
                    "type": "integer"
                }
            }
        },
        "model.PracticeDays": {
            "type": "object",
            "required": [
                "day"
            ],
            "properties": {
                "day": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "model.PracticeShedule": {
            "type": "object",
            "properties": {
                "day": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "practice_config_id": {
                    "type": "integer"
                }
            }
        },
        "model.Practices": {
            "type": "object",
            "required": [
                "end",
                "practice_name",
                "start"
            ],
            "properties": {
                "end": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "practice_name": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                }
            }
        },
        "model.ResponseUser": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "model.ResponseUserCreateGroupMPT": {
            "type": "object",
            "properties": {
                "answer": {
                    "$ref": "#/definitions/model.ResponseUser"
                },
                "data": {
                    "$ref": "#/definitions/model.GroupMPT"
                }
            }
        },
        "model.ResponseUserCreateGroupMPTArr": {
            "type": "object",
            "properties": {
                "answer": {
                    "$ref": "#/definitions/model.ResponseUser"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.GroupMPT"
                    }
                }
            }
        },
        "model.ResponseUserCreateGroupMarlo": {
            "type": "object",
            "properties": {
                "answer": {
                    "$ref": "#/definitions/model.ResponseUser"
                },
                "data": {
                    "$ref": "#/definitions/model.GroupMarlo"
                }
            }
        },
        "model.ResponseUserCreateGroupMarloArr": {
            "type": "object",
            "properties": {
                "answer": {
                    "$ref": "#/definitions/model.ResponseUser"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.GroupMarlo"
                    }
                }
            }
        },
        "model.ResponseUserCreateLogs": {
            "type": "object",
            "properties": {
                "answer": {
                    "$ref": "#/definitions/model.ResponseUser"
                },
                "data": {
                    "$ref": "#/definitions/model.Logs"
                }
            }
        },
        "model.ResponseUserCreateLogsArr": {
            "type": "object",
            "properties": {
                "answer": {
                    "$ref": "#/definitions/model.ResponseUser"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Logs"
                    }
                }
            }
        },
        "model.ResponseUserCreatePractice": {
            "type": "object",
            "properties": {
                "answer": {
                    "$ref": "#/definitions/model.ResponseUser"
                },
                "data": {
                    "$ref": "#/definitions/model.Practices"
                }
            }
        },
        "model.ResponseUserCreatePracticeArr": {
            "type": "object",
            "properties": {
                "answer": {
                    "$ref": "#/definitions/model.ResponseUser"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Practices"
                    }
                }
            }
        },
        "model.ResponseUserCreatePracticeConfig": {
            "type": "object",
            "properties": {
                "answer": {
                    "$ref": "#/definitions/model.ResponseUser"
                },
                "data": {
                    "$ref": "#/definitions/model.PracticeConfig"
                }
            }
        },
        "model.ResponseUserCreatePracticeConfigArr": {
            "type": "object",
            "properties": {
                "answer": {
                    "$ref": "#/definitions/model.ResponseUser"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PracticeConfig"
                    }
                }
            }
        },
        "model.ResponseUserCreatePracticedays": {
            "type": "object",
            "properties": {
                "answer": {
                    "$ref": "#/definitions/model.ResponseUser"
                },
                "data": {
                    "$ref": "#/definitions/model.PracticeDays"
                }
            }
        },
        "model.ResponseUserCreatePracticedaysArr": {
            "type": "object",
            "properties": {
                "answer": {
                    "$ref": "#/definitions/model.ResponseUser"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PracticeDays"
                    }
                }
            }
        },
        "model.ResponseUserCreateStatus": {
            "type": "object",
            "properties": {
                "answer": {
                    "$ref": "#/definitions/model.ResponseUser"
                },
                "data": {
                    "$ref": "#/definitions/model.Status"
                }
            }
        },
        "model.ResponseUserCreateStatusArr": {
            "type": "object",
            "properties": {
                "answer": {
                    "$ref": "#/definitions/model.ResponseUser"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Status"
                    }
                }
            }
        },
        "model.ResponseUserCreateUser": {
            "type": "object",
            "properties": {
                "answer": {
                    "$ref": "#/definitions/model.ResponseUser"
                },
                "data": {
                    "$ref": "#/definitions/model.User"
                }
            }
        },
        "model.ResponseUserCreateUserArr": {
            "type": "object",
            "properties": {
                "answer": {
                    "$ref": "#/definitions/model.ResponseUser"
                },
                "data_arr": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.User"
                    }
                }
            }
        },
        "model.ResponseUserCreatepracticeShedule": {
            "type": "object",
            "properties": {
                "answer": {
                    "$ref": "#/definitions/model.ResponseUser"
                },
                "data": {
                    "$ref": "#/definitions/model.PracticeShedule"
                }
            }
        },
        "model.ResponseUserCreatepracticeSheduleArr": {
            "type": "object",
            "properties": {
                "answer": {
                    "$ref": "#/definitions/model.ResponseUser"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PracticeShedule"
                    }
                }
            }
        },
        "model.Status": {
            "type": "object",
            "required": [
                "status_name"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "status_name": {
                    "type": "string"
                }
            }
        },
        "model.User": {
            "type": "object",
            "required": [
                "can_enter",
                "date_of_birth",
                "discord",
                "email",
                "keycloack_id",
                "name",
                "patronymic",
                "status_id",
                "surname",
                "telegram"
            ],
            "properties": {
                "can_enter": {
                    "type": "boolean"
                },
                "date_of_birth": {
                    "type": "string"
                },
                "discord": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "keycloack_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "patronymic": {
                    "type": "string"
                },
                "status_id": {
                    "type": "integer"
                },
                "surname": {
                    "type": "string"
                },
                "telegram": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "\"Bearer\" токен от keycloak в header \"Authorization\". При вставке из flow, дописывать слово - Bearer",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MarloService API",
	Description:      "This is a sample MarloService API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
